#spring.application.name=tvet-mis-backend-application

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/db_tvet_mis?rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql = false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

#---cross orgin details -----
allowed.origin=*

# For multipart file uploads
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
# For base64 approach
profile.image.upload-dir=D:/uploads/profile-images/
# For profile image URLs
profile.image.base-url=http://localhost:8080/

# File path
file.store.path = D:/uploaded_documents
#---token details -----
jwt.secret=703dee9905d3400a03d82258181cca08c99dbd31bf413277586da5bef735f21c
#1 hour
jwt.access-token-expiration=3600000  
#2 hours
jwt.refresh-token-expiration=7200000 
# Token Expiration password reset(1 hour)
app.password-reset.token-expiration=3600000
app.secret-hex=6D5A7134743777217A25432A462D4A614E645267556B586E3272357538702F31

# Gmail SMTP Configuration
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=thinleywangchuk2097@gmail.com
#spring.mail.password=yuezzetmbhajpuob 
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Mailtrap SMTP Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=f3867aac3fa59c  
spring.mail.password=c762847115df8a 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true  # Enable TLS

# Enable debug logging
logging.level.org.springframework.mail=DEBUG
spring.mail.debug=true
logging.level.org.springframework.security=DEBUG



#Bhutan NDI stagging credentials details
ndi.token-api-url=https://staging.bhutanndi.com/authentication/v1/authenticate
ndi.client-id=3tq7ho23g5risndd90a76jre5f
ndi.client-secret=111rvn964mucumr6c3qq3n2poilvq5v92bkjh58p121nmoverquh
ndi.grant-type=client_credentials
ndi.create-proof-request-url=https://demo-client.bhutanndi.com/verifier/v1/proof-request
ndi.schema-name-url=https://dev-schema.ngotag.com/schemas/c7952a0a-e9b5-4a4b-a714-1e5d0a1ae076

#birms stagging payment details
birms.token-api=https://birmsstagging.drc.gov.bt/api-services/core-module/api/v1/auth/external-users/logMeIn
birms.client-key=tvetmisbirms
birms.client-secret=N7@vQ2#kL9!rT4$zX8^m
birms.platform=TVET MIS
birms.agency-code=BTH5338
birms.service-code=100578
birms.description=tvet renewal and registration fee
birms.payment-advice-create-url=https://birmsstagging.drc.gov.bt/api-services/moesd-service/api/v1/paymentdetails/create
birms.payment-cancel-url=https://birmsstagging.drc.gov.bt/api-services/moesd-service/api/v1/paymentdetails/cancel
birms.receipt-encoded-pdf-url=https://birmsstagging.drc.gov.bt/api-services/moesd-service/api/v1/paymentdetails/receipt-encoded-pdf/{receiptNo}
#birms stagging ends

#staging DCRC api details 
datahub.token-api=https://stg-sso.tech.gov.bt/oauth2/token 
datahub.citizen-api=https://staging-datahub-apim.tech.gov.bt/dcrc_citizen_details_api/1.0.0/citizendetails/
datahub.consumer-key=K3vCltl2lPmR0Lsiivzjt6YJOTEa
datahub.consumer-secret=2OsRvi9sAQEgHHq0InAFDg49CZMa

#staging IBLS api details
datahub.ibls-token-api=https://stg-sso.tech.gov.bt/oauth2/token 
datahub.ibls-license-api= https://staging-datahub-apim.tech.gov.bt/moea_licenseinformationapi/1.0.0/DetailsAgainstLicense/
datahub.ibls-consumer-key=K3vCltl2lPmR0Lsiivzjt6YJOTEa
datahub.ibls-consumer-secret=2OsRvi9sAQEgHHq0InAFDg49CZMa

#staging gyalsung api details
gyalsung-token-api=https://test.ns.bt/api/enrolment/deferment/exemption/gyalsung_api/token
gyalsung-data-api=https://test.ns.bt/api/enrolment/deferment/exemption/gyalsung_api/getGyalsungDetails/
gyalsung-consumer-key=s9XenM2wRebuzVv2tR9y
gyalsung-consumer-secret=HlYhBYaBUQ9PxPztoCncaqav

#staging foreign workers management system employer/employee/job seeker api details
mis-foreign-worker-api= https://staging-datahub-apim.tech.gov.bt/tvet_misinfoapi/1.0.0/foreignworker/
mis-employer-api= https://staging-datahub-apim.tech.gov.bt/tvet_misinfoapi/1.0.0/employerinfo/
mis-jobseek-api= https://staging-datahub-apim.tech.gov.bt/tvet_misinfoapi/1.0.0/jobseekerinfo/
mis-token-api=https://stg-sso.tech.gov.bt/oauth2/token
mis-consumer-key=qndxsR0rFe21zTb8Qu3WIZl2Qk4a
mis-consumer-secret=lRsZKT0D0xAUiHMGJIHwFERXe0Qa

#bcsea api details
bcsea-token-api=https://stg-sso.tech.gov.bt/oauth2/token
bcsea-student-api=https://staging-datahub-apim.tech.gov.bt/bcsea_studentresultapi/1.0.0/studentresults/
bcsea-consumer-key=INE3RmgyNRjVx2SvsQ4KcscozXQa
bcsea-consumer-secret=Rt4Yhfp7Gf0iOX7vIemXl1IDcxYa
