# Base configuration - common for all environments
spring.application.name=tvet-mis-backend-application
server.port=8080

# Set default profile to dev
spring.profiles.active=dev

# Set profile active to prod
#spring.profiles.active=prod

# Common logging
logging.level.org.springframework.web=INFO