package com.moesd.tvet.mis.backend.application.repository;

import java.util.List;
import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import com.moesd.tvet.mis.backend.application.model.AccreditedCourse;
import jakarta.persistence.Tuple;


public interface AccreditedCourseRepository extends JpaRepository<AccreditedCourse,Long> {
	@Query(value =  
			"SELECT "
					+ "  ac.id, "
					+ "  ac.application_no, "
					+ "  ac.institute_id, "
					+ "  ac.course_id, "
					+ "  ac.course_fee, "
					+ "  ac.is_active, "
					+ "  ac.sector_id, "
					+ "  ac.registration_date, "
					+ "  ac.validity_date, "
					+ "  ac.status_id, "
					+ "  ac.created_by, "
					+ "  ac.created_at, "
					+ "  ac.updated_by, "
					+ "  ac.updated_at, "
					+ "  ac.curriculum_id, "
					+ "  ir.proposed_institute_name, "
					+ "  ir.registration_no, "
					+ "  cd.curriculum_name, "
					+ "  (SELECT "
					+ "    IFNULL( "
					+ "      JSON_ARRAYAGG( "
					+ "        JSON_OBJECT( "
					+ "          'id', d.id, "
					+ "          'documentName', d.document_name, "
					+ "          'url', d.upload_url "
					+ "        ) "
					+ "      ), "
					+ "      JSON_ARRAY() "
					+ "    ) "
					+ "  FROM tbl_document_master d "
					+ "  WHERE d.application_no = ac.application_no) AS documents, "
					+ "  (SELECT "
					+ "    IFNULL( "
					+ "      JSON_ARRAYAGG( "
					+ "        JSON_OBJECT( "
					+ "          'id', qs.id, "
					+ "          'standardId', qs.standard_id, "
					+ "          'responseId', qs.response_id, "
					+ "          'remarks', qs.remarks "
					+ "        ) "
					+ "      ), "
					+ "      JSON_ARRAY() "
					+ "    ) "
					+ "  FROM tbl_accredited_course_quality_standard_Response qs "
					+ "  WHERE qs.application_no = ac.application_no) AS quality_standard_responses "
					+ " "
					+ "FROM "
					+ "  tbl_accredited_course_dtls ac "
					+ "  LEFT JOIN tbl_institute_registration_dtls ir "
					+ "    ON ac.institute_id = ir.institute_id "
					+ "  LEFT JOIN tbl_curriculum_development cd "
					+ "    ON ac.curriculum_id = cd.id "
					+ "WHERE ac.application_no = ?", nativeQuery = true)
		List<Tuple> findByInstituteAccreditedCourseApplicationNo(String application_no);
	
		@Query(value =  
				"SELECT "
						+ "  ac.id, "
						+ "  ac.application_no, "
						+ "  ac.institute_id, "
						+ "  ac.course_id, "
						+ "  ac.course_fee, "
						+ "  ac.is_active, "
						+ "  ac.registration_date, "
						+ "  ac.validity_date, "
						+ "  ac.sector_id, "
						+ "  ac.curriculum_id, "
						+ "  ac.status_id, "
						+ "  ac.created_at, "
						+ "  ac.created_by, "
						+ "  ac.updated_at, "
						+ "  ac.updated_by, "
						+ "  ir.proposed_institute_name, "
						+ "  ir.registration_no, "
						+ "  cd.curriculum_name, "
						+ "  om.occupation_name AS course_name, "
						+ "  (SELECT "
						+ "    JSON_ARRAYAGG( "
						+ "      JSON_OBJECT( "
						+ "        'id', "
						+ "        qs.id, "
						+ "        'standardId', "
						+ "        qs.standard_id, "
						+ "        'responseId', "
						+ "        qs.response_id, "
						+ "        'remarks', "
						+ "        qs.remarks "
						+ "      ) "
						+ "    ) "
						+ "  FROM "
						+ "    tbl_accredited_course_quality_standard_Response qs "
						+ "  WHERE qs.application_no = ac.application_no) AS quality_standard_responses, "
						+ "  (SELECT "
						+ "    JSON_ARRAYAGG( "
						+ "      JSON_OBJECT( "
						+ "        'id', "
						+ "        d.id, "
						+ "        'documentName', "
						+ "        d.document_name, "
						+ "        'url', "
						+ "        d.upload_url "
						+ "      ) "
						+ "    ) "
						+ "  FROM "
						+ "    tbl_document_master d "
						+ "  WHERE d.application_no = ac.application_no) AS documents "
						+ "FROM "
						+ "  tbl_accredited_course_dtls ac "
						+ "  LEFT JOIN tbl_institute_registration_dtls ir "
						+ "    ON ac.institute_id = ir.institute_id "
						+ "  LEFT JOIN tbl_curriculum_development cd "
						+ "    ON ac.curriculum_id = cd.id "
						+ "  LEFT JOIN tbl_occupation_master om "
						+ "    ON om.id = ac.course_id "
						+ "  LEFT JOIN tbl_user ut "
						+ "    ON ut.user_id = ir.registration_no "
						+ "WHERE ut.user_id = ?", nativeQuery = true)
		List<Tuple> getAccreditedCourseDetailsByUserId(String user_id);
		
		Optional<AccreditedCourse> findByApplicationNo(String applicationNo);
		
		@Query(value =  
				"SELECT "
						+ "  a.id, "
						+ "  b.occupation_name AS course_name "
						+ "FROM "
						+ "  tbl_accredited_course_dtls a "
						+ "  LEFT JOIN tbl_occupation_master b "
						+ "    ON a.course_id = b.id "
						+ "  LEFT JOIN tbl_institute_registration_dtls c "
						+ "    ON c.institute_id = a.institute_id "
						+ "  LEFT JOIN tbl_user d "
						+ "    ON c.registration_no = d.user_id "
						+ "WHERE a.status_id = 57 "
						+ "  AND d.user_id = ?", nativeQuery = true)
		List<Tuple> getAccreditedApprovedCourseByUserId(String user_id);
}
