package com.moesd.tvet.mis.backend.application.repository;

import java.util.List;
import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import com.moesd.tvet.mis.backend.application.model.AccreditedCourse;
import jakarta.persistence.Tuple;


public interface AccreditedCourseRepository extends JpaRepository<AccreditedCourse,Long> {
	@Query(value =  
			"SELECT "
					+ "  ac.id, "
					+ "  ac.application_no, "
					+ "  ac.institute_id, "
					+ "  ac.course_id, "
					+ "  ac.course_fee, "
					+ "  ac.class_no, "
					+ "  ac.workshop_no, "
					+ "  ac.training_lab_no, "
					+ "  ac.curriculum_type_id, "
					+ "  ac.equipment_tool, "
					+ "  ac.first_aid_facility, "
					+ "  ac.toilet_facility, "
					+ "  ac.lighting_power, "
					+ "  ac.fire_safety, "
					+ "  ac.trainer_trainee_ratio_theory, "
					+ "  ac.trainer_trainee_ratio_practical, "
					+ "  ac.max_no_trainees, "
					+ "  ac.present_no_trainee, "
					+ "  ac.applicant_name, "
					+ "  ac.institute_head, "
					+ "  ac.is_active, "
					+ "  ac.registration_date, "
					+ "  ac.validity_date, "
					+ "  ac.sector_id, "
					+ "  ir.proposed_institute_name, "
					+ "  ir.registration_no, "
					+ "  cd.curriculum_name, "
					+ "  ac.status_id, "
					+ "  ac.created_at, "
					+ "  ac.created_by, "
					+ "  ac.updated_at, "
					+ "  ac.updated_by, "
					+ "  (SELECT "
					+ "    JSON_ARRAYAGG( "
					+ "      JSON_OBJECT( "
					+ "        'id', "
					+ "        c.id, "
					+ "        'certificationCode', "
					+ "        c.certification_code, "
					+ "        'certificationModule', "
					+ "        c.certification_module, "
					+ "        'certificationLevelId', "
					+ "        c.certification_level_id "
					+ "      ) "
					+ "    ) "
					+ "  FROM "
					+ "    tbl_accredited_certification_dtls c "
					+ "  WHERE c.application_no = ac.application_no) AS certifications, "
					+ "  (SELECT "
					+ "    JSON_ARRAYAGG( "
					+ "      JSON_OBJECT( "
					+ "        'id', "
					+ "        cur.id, "
					+ "        'moduleNo', "
					+ "        cur.module_no, "
					+ "        'moduleName', "
					+ "        cur.module_name, "
					+ "        'ncsCode', "
					+ "        cur.ncs_code, "
					+ "        'theoryHour', "
					+ "        cur.theory_hour, "
					+ "        'practicalHour', "
					+ "        cur.practical_hour, "
					+ "        'ojtHour', "
					+ "        cur.ojt_hour "
					+ "      ) "
					+ "    ) "
					+ "  FROM "
					+ "    tbl_accredited_curriculum_dtls cur "
					+ "  WHERE cur.application_no = ac.application_no) AS curriculums, "
					+ "  (SELECT "
					+ "    JSON_ARRAYAGG( "
					+ "      JSON_OBJECT( "
					+ "        'id', "
					+ "        t.id, "
					+ "        'trainerName', "
					+ "        t.trainer_name, "
					+ "        'acamedicProfessional', "
					+ "        t.acamedic_professional, "
					+ "        'industrialExperience', "
					+ "        t.industrial_experience, "
					+ "        'teachingExperience', "
					+ "        t.teaching_experience, "
					+ "        'subjectTaught', "
					+ "        t.subject_taught, "
					+ "        'teachingHour', "
					+ "        t.teaching_hour "
					+ "      ) "
					+ "    ) "
					+ "  FROM "
					+ "    tbl_accredited_trainer_dtls t "
					+ "  WHERE t.application_no = ac.application_no) AS trainers, "
					+ "  (SELECT "
					+ "    JSON_ARRAYAGG( "
					+ "      JSON_OBJECT( "
					+ "        'id', "
					+ "        d.id, "
					+ "        'documentName', "
					+ "        d.document_name, "
					+ "        'url', "
					+ "        d.upload_url "
					+ "      ) "
					+ "    ) "
					+ "  FROM "
					+ "    tbl_document_master d "
					+ "  WHERE d.application_no = ac.application_no) AS documents "
					+ "FROM "
					+ "  tbl_accredited_course_dtls ac "
					+ "  LEFT JOIN tbl_institute_registration_dtls ir "
					+ "    ON ac.institute_id = ir.institute_id "
					+ "    LEFT JOIN tbl_curriculum_development cd "
					+ "    ON ac.curriculum_type_id= cd.id "
					+ "WHERE ac.application_no = ?", nativeQuery = true)
		List<Tuple> findByInstituteAccreditedCourseApplicationNo(String application_no);
	
		@Query(value =  
				"SELECT "
						+ "  ac.id, "
						+ "  ac.application_no, "
						+ "  ac.institute_id, "
						+ "  ac.course_id, "
						+ "  ac.course_fee, "
						+ "  ac.is_active, "
						+ "  ac.registration_date, "
						+ "  ac.validity_date, "
						+ "  ac.sector_id, "
						+ "  ac.curriculum_id, "
						+ "  ac.status_id, "
						+ "  ac.created_at, "
						+ "  ac.created_by, "
						+ "  ac.updated_at, "
						+ "  ac.updated_by, "
						+ "  ir.proposed_institute_name, "
						+ "  ir.registration_no, "
						+ "  cd.curriculum_name, "
						+ "  om.occupation_name AS course_name, "
						+ "  (SELECT "
						+ "    JSON_ARRAYAGG( "
						+ "      JSON_OBJECT( "
						+ "        'id', "
						+ "        qs.id, "
						+ "        'standardId', "
						+ "        qs.standard_id, "
						+ "        'responseId', "
						+ "        qs.response_id, "
						+ "        'remarks', "
						+ "        qs.remarks "
						+ "      ) "
						+ "    ) "
						+ "  FROM "
						+ "    tbl_accredited_course_quality_standard_Response qs "
						+ "  WHERE qs.application_no = ac.application_no) AS quality_standard_responses, "
						+ "  (SELECT "
						+ "    JSON_ARRAYAGG( "
						+ "      JSON_OBJECT( "
						+ "        'id', "
						+ "        d.id, "
						+ "        'documentName', "
						+ "        d.document_name, "
						+ "        'url', "
						+ "        d.upload_url "
						+ "      ) "
						+ "    ) "
						+ "  FROM "
						+ "    tbl_document_master d "
						+ "  WHERE d.application_no = ac.application_no) AS documents "
						+ "FROM "
						+ "  tbl_accredited_course_dtls ac "
						+ "  LEFT JOIN tbl_institute_registration_dtls ir "
						+ "    ON ac.institute_id = ir.institute_id "
						+ "  LEFT JOIN tbl_curriculum_development cd "
						+ "    ON ac.curriculum_id = cd.id "
						+ "  LEFT JOIN tbl_occupation_master om "
						+ "    ON om.id = ac.course_id "
						+ "  LEFT JOIN tbl_user ut "
						+ "    ON ut.user_id = ir.registration_no "
						+ "WHERE ut.user_id = ?", nativeQuery = true)
		List<Tuple> getAccreditedCourseDetailsByUserId(String user_id);
		
		Optional<AccreditedCourse> findByApplicationNo(String applicationNo);
}
