package com.moesd.tvet.mis.backend.application.repository;

import java.util.List;
import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import com.moesd.tvet.mis.backend.application.model.AccreditedCourse;
import jakarta.persistence.Tuple;


public interface AccreditedCourseRepository extends JpaRepository<AccreditedCourse,Long> {
	@Query(value =  
			"SELECT "
					+ "  ac.id, "
					+ "  ac.application_no, "
					+ "  ac.institute_id, "
					+ "  ac.fees_per_trainee, "
					+ "  ac.enrolment_capacity, "
					+ "  ac.registration_date, "
					+ "  ac.validity_date, "
					+ "  ac.status_id, "
					+ "  ac.curriculum_id, "
					+ "  ac.lead_trainer_cid_no, "
					+ "  ac.lead_trainer_name, "
					+ "  ac.professional_experience, "
					+ "  ac.qualification_id, "
					+ "  ac.gender_id, "
					+ "  ncs.sector_id, "
					+ "  ncs.occupation_id, "
					+ "  ncs.programme_title, "
					+ "  ir.proposed_institute_name, "
					+ "  ir.registration_no, "
					+ "  (SELECT "
					+ "    IFNULL( "
					+ "      JSON_ARRAYAGG( "
					+ "        JSON_OBJECT( "
					+ "          'id', "
					+ "          d.id, "
					+ "          'documentName', "
					+ "          d.document_name, "
					+ "          'url', "
					+ "          d.upload_url "
					+ "        ) "
					+ "      ), "
					+ "      JSON_ARRAY() "
					+ "    ) "
					+ "  FROM "
					+ "    tbl_document_master d "
					+ "  WHERE d.application_no = ac.application_no) AS documents, "
					+ "  (SELECT "
					+ "    IFNULL( "
					+ "      JSON_ARRAYAGG( "
					+ "        JSON_OBJECT( "
					+ "          'id', "
					+ "          qs.id, "
					+ "          'standardId', "
					+ "          qs.standard_id, "
					+ "          'responseId', "
					+ "          qs.response_id, "
					+ "          'remarks', "
					+ "          qs.remarks "
					+ "        ) "
					+ "      ), "
					+ "      JSON_ARRAY() "
					+ "    ) "
					+ "  FROM "
					+ "    tbl_accredited_course_quality_standard_response qs "
					+ "  WHERE qs.application_no = ac.application_no) AS quality_standard_responses "
					+ "FROM "
					+ "  tbl_accredited_course_dtls ac "
					+ "  LEFT JOIN tbl_curriculum_development cd "
					+ "    ON cd.id = ac.curriculum_id "
					+ "  LEFT JOIN tbl_ncs_app_dtls ncs "
					+ "    ON ncs.id = cd.programme_id "
					+ "  LEFT JOIN tbl_institute_registration_dtls ir "
					+ "    ON ac.institute_id = ir.institute_id "
					+ "WHERE ac.application_no = ?", nativeQuery = true)
		List<Tuple> findByInstituteAccreditedCourseApplicationNo(String application_no);
	
		@Query(value =  
				"SELECT "
						+ "  ac.id, "
						+ "  ac.application_no, "
						+ "  ac.institute_id, "
						+ "  ac.fees_per_trainee, "
						+ "  ac.enrolment_capacity, "
						+ "  ac.registration_date, "
						+ "  ac.validity_date, "
						+ "  ac.curriculum_id, "
						+ "  ac.status_id, "
						+ "  ac.lead_trainer_cid_no, "
						+ "  ac.lead_trainer_name, "
						+ "  ac.professional_experience, "
						+ "  ac.qualification_id, "
						+ "  ac.gender_id, "
						+ "  ir.proposed_institute_name, "
						+ "  ir.registration_no, "
						+ "  ncs.sector_id, "
						+ "  ncs.occupation_id, "
						+ "  ncs.programme_title, "
						+ "  ncs.certification_id, "
						+ "  (SELECT "
						+ "    JSON_ARRAYAGG( "
						+ "      JSON_OBJECT( "
						+ "        'id', "
						+ "        qs.id, "
						+ "        'standardId', "
						+ "        qs.standard_id, "
						+ "        'responseId', "
						+ "        qs.response_id, "
						+ "        'remarks', "
						+ "        qs.remarks "
						+ "      ) "
						+ "    ) "
						+ "  FROM "
						+ "    tbl_accredited_course_quality_standard_response qs "
						+ "  WHERE qs.application_no = ac.application_no) AS quality_standard_responses, "
						+ "  (SELECT "
						+ "    JSON_ARRAYAGG( "
						+ "      JSON_OBJECT( "
						+ "        'id', "
						+ "        d.id, "
						+ "        'documentName', "
						+ "        d.document_name, "
						+ "        'url', "
						+ "        d.upload_url "
						+ "      ) "
						+ "    ) "
						+ "  FROM "
						+ "    tbl_document_master d "
						+ "  WHERE d.application_no = ac.application_no) AS documents "
						+ "FROM "
						+ "  tbl_accredited_course_dtls ac "
						+ "  LEFT JOIN tbl_curriculum_development cd "
						+ "    ON ac.curriculum_id = cd.id "
						+ "  LEFT JOIN tbl_ncs_app_dtls ncs "
						+ "    ON ncs.id = cd.programme_id "
						+ "  LEFT JOIN tbl_institute_registration_dtls ir "
						+ "    ON ac.institute_id = ir.institute_id "
						+ "  LEFT JOIN tbl_user ur "
						+ "    ON ur.user_id = ir.registration_no "
						+ "WHERE ur.user_id = ?", nativeQuery = true)
		List<Tuple> getAccreditedCourseDetailsByUserId(String user_id);
		
		Optional<AccreditedCourse> findByApplicationNo(String applicationNo);
		
		@Query(value =  
				"SELECT "
						+ "  ncs.id, "
						+ "  a.fees_per_trainee, "
						+ "  a.enrolment_capacity, "
						+ "  b.certificate_level_id, "
						+ "  ncs.programme_title "
						+ "FROM "
						+ "  tbl_accredited_course_dtls a "
						+ "  LEFT JOIN tbl_curriculum_development b "
						+ "    ON a.curriculum_id = b.id "
						+ "  LEFT JOIN tbl_ncs_app_dtls ncs "
						+ "    ON ncs.id = b.programme_id "
						+ "  LEFT JOIN tbl_institute_registration_dtls d "
						+ "    ON d.institute_id = a.institute_id "
						+ "  LEFT JOIN tbl_user e "
						+ "    ON d.registration_no = e.user_id "
						+ "WHERE a.status_id IN(57, 126) "
						+ "  AND e.user_id = ?", nativeQuery = true)
		List<Tuple> getAccreditedApprovedCourseByUserId(String user_id);
		
		@Query(value =  
				"SELECT "
						+ "  a.id, "
						+ "  ncs.programme_title AS course_name "
						+ "FROM "
						+ "  tbl_accredited_course_dtls a "
						+ "  LEFT JOIN tbl_curriculum_development b "
						+ "    ON a.curriculum_id = b.id "
						+ "  LEFT JOIN tbl_ncs_app_dtls ncs "
						+ "    ON ncs.id = b.programme_id "
						+ "WHERE a.institute_id = ? "
						+ "  AND a.status_id = 57", nativeQuery = true)
		List<Tuple> getAccreditedCourseByInstituteId(String institute_id);
		
		@Query(value =  
				"SELECT "
						+ "  a.curriculum_id "
						+ "FROM "
						+ "  tbl_accredited_course_dtls a "
						+ "  LEFT JOIN tbl_institute_registration_dtls b "
						+ "    ON a.institute_id = b.institute_id "
						+ "WHERE a.curriculum_id = ? "
						+ "  AND b.registration_no = ?", nativeQuery = true)
		List<Tuple> curriculumExist(Long curriculumId, String registration_no);
		
		
		
		
}
