package com.moesd.tvet.mis.backend.application.repository;

import java.util.List;
import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import com.moesd.tvet.mis.backend.application.model.CourseEnrollmentApp;
import jakarta.persistence.Tuple;

public interface CourseEnrollmentAppRepository extends JpaRepository<CourseEnrollmentApp, Long> {
	@Query(value = "SELECT "
			+ "  a.* "
			+ "FROM "
			+ "  tbl_programme_announcement_dtls a "
			+ "  LEFT JOIN tbl_institute_registration_dtls b "
			+ "    ON a.institute_id = b.institute_id "
			+ "  LEFT JOIN tbl_user c "
			+ "    ON b.registration_no = c.user_id "
			+ "WHERE c.user_id = ? "
			+ "  AND a.service_id = ?", nativeQuery = true)
	List<Tuple> getCourseDetailsAnnouncementByUserId(String user_id, String service_id);
	
	@Query(value =  "SELECT "
			+ "  a.*, "
			+ "  e.proposed_institute_name AS institute_name, "
			+ "  b.entry_requirement, "
			+ "  CASE "
			+ "    WHEN a.service_id = 37 "
			+ "    THEN c.programme_title "
			+ "    WHEN a.service_id = 38 "
			+ "    THEN nc.programme_title "
			+ "    WHEN a.service_id = 39 "
			+ "    THEN d.programme_title "
			+ "  END AS course_name, "
			+ "  COALESCE (t.total_applied, 0) AS total_applied "
			+ "FROM "
			+ "  tbl_programme_announcement_dtls a "
			+ "  LEFT JOIN tbl_curriculum_development b "
			+ "    ON a.programme_id = b.programme_id "
			+ "  LEFT JOIN tbl_ncs_app_dtls c "
			+ "    ON c.id = b.programme_id "
			+ "  LEFT JOIN tbl_accredited_course_dtls ac "
			+ "    ON ac.curriculum_id = b.id "
			+ "  LEFT JOIN tbl_non_accredited_course_dtls nc "
			+ "    ON a.programme_id = nc.id "
			+ "  LEFT JOIN tbl_ncs_app_dtls d "
			+ "    ON d.id = a.programme_id "
			+ "  LEFT JOIN tbl_institute_registration_dtls e "
			+ "    ON e.institute_id = a.institute_id "
			+ "  LEFT JOIN "
			+ "    (SELECT "
			+ "      course_enrol_app_no, "
			+ "      COUNT(*) AS total_applied "
			+ "    FROM "
			+ "      tbl_programme_trainee_enrollment_dtls "
			+ "    GROUP BY course_enrol_app_no) t "
			+ "    ON t.course_enrol_app_no = a.application_no "
			+ "WHERE a.service_id IN (37, 38, 39) "
			+ "  AND a.application_end_date >= CURRENT_DATE", nativeQuery = true)
	List<Tuple> getAllCourseAnnouncement();
	
	@Query(value = "SELECT "
			+ "  a.* "
			+ "FROM "
			+ "  tbl_dropdown_child_master a "
			+ "WHERE a.id IN(108, 109, 110, 111, 112, 35, 36)", nativeQuery = true)
	List<Tuple> getAllCertificateLevels();
	
	
	@Query(value =  "SELECT "
			+ "  a.*, "
			+ "  e.registration_no, "
			+ "  e.proposed_institute_name AS institute_name, "
			+ "  e.mobile_no AS institue_mobile_number, "
			+ "  e.email_id AS institute_email, "
			+ "  dcd.name AS certification_name, "
			+ "  CASE "
			+ "    WHEN a.service_id = 37 "
			+ "    THEN c.programme_title "
			+ "    WHEN a.service_id = 38 "
			+ "    THEN nc.programme_title "
			+ "    WHEN a.service_id = 39 "
			+ "    THEN d.programme_title "
			+ "  END AS course_name "
			+ "FROM "
			+ "  tbl_programme_announcement_dtls a "
			+ "  LEFT JOIN tbl_curriculum_development cd "
			+ "  ON cd.programme_id = a.programme_id "
			+ "  LEFT JOIN tbl_accredited_course_dtls b "
			+ "    ON cd.id = b.curriculum_id "
			+ "  LEFT JOIN tbl_ncs_app_dtls c "
			+ "    ON c.id = cd.programme_id "
			+ "  LEFT JOIN tbl_non_accredited_course_dtls nc "
			+ "    ON a.programme_id = nc.id "
			+ "  LEFT JOIN tbl_ncs_app_dtls d "
			+ "    ON d.id = a.programme_id "
			+ "  LEFT JOIN tbl_dropdown_child_master dcd "
			+ "    ON dcd.id = a.certification_level_id "
			+ "  LEFT JOIN tbl_institute_registration_dtls e "
			+ "    ON e.institute_id = a.institute_id "
			+ "WHERE a.application_no = ? "
			+ "  AND a.service_id IN(37, 38, 39)", nativeQuery = true)
	List<Tuple> getCourseAnnouncementByApplicationNo(String application_no);
	
	@Query(value =  "SELECT "
			+ "  a.*, "
			+ "  cd.name AS certification_name, "
			+ "  CASE "
			+ "    WHEN a.service_id = 41 "
			+ "    THEN c.programme_title "
			+ "    WHEN a.service_id = 42 "
			+ "    THEN d.programme_title "
			+ "  END AS course_name "
			+ "FROM "
			+ "  tbl_programme_announcement_dtls a "
			+ "  LEFT JOIN tbl_curriculum_development cd "
			+ "    ON cd.programme_id = a.programme_id "
			+ "  LEFT JOIN tbl_accredited_course_dtls b "
			+ "    ON cd.id = b.curriculum_id "
			+ "  LEFT JOIN tbl_ncs_app_dtls c "
			+ "    ON c.id = cd.programme_id "
			+ "  LEFT JOIN tbl_ncs_app_dtls d "
			+ "    ON d.id = cd.programme_id "
			+ "  LEFT JOIN tbl_dropdown_child_master cd "
			+ "    ON cd.id = a.certification_level_id "
			+ "WHERE a.application_no = ? "
			+ "  AND a.service_id IN (41, 42)", nativeQuery = true)
	List<Tuple> getReAssessmentAnnouncementByApplicationNo(String application_no);
	
	Optional<CourseEnrollmentApp> findByApplicationNo(String application_no);
	
	@Query(value = "SELECT "
			+ "  a.* "
			+ "FROM "
			+ "  tbl_service_master a "
			+ "WHERE a.id IN (41, 42)", nativeQuery = true)
	List<Tuple> getReAssessmentServiceName();
	
	
	@Query(value = "SELECT "
			+ "  a.id, "
			+ "  a.cid_no, "
			+ "  a.applicant_name, "
			+ "  a.gender_id, "
			+ "  a.academic_qualification_id, "
			+ "  a.email_id, "
			+ "  a.mobile_no, "
			+ "  a.guardian_name, "
			+ "  a.guardian_mobile_no, "
			+ "  (SELECT "
			+ "    IFNULL( "
			+ "      JSON_ARRAYAGG( "
			+ "        JSON_OBJECT( "
			+ "          'id', "
			+ "          sm.id, "
			+ "          'markScore', "
			+ "          sm.mark_score, "
			+ "          'subject', "
			+ "          sm.subject, "
			+ "          'traineeId', "
			+ "          sm.trainee_id "
			+ "        ) "
			+ "      ), "
			+ "      JSON_ARRAY() "
			+ "    ) "
			+ "  FROM "
			+ "    tbl_programme_trainee_enrollment_subject_marks sm "
			+ "  WHERE sm.trainee_id = a.id) AS trainee_marks, "
			+ "  (SELECT "
			+ "    IFNULL( "
			+ "      JSON_ARRAYAGG( "
			+ "        JSON_OBJECT( "
			+ "          'id', "
			+ "          d.id, "
			+ "          'documentName', "
			+ "          d.document_name, "
			+ "          'url', "
			+ "          d.upload_url "
			+ "        ) "
			+ "      ), "
			+ "      JSON_ARRAY() "
			+ "    ) "
			+ "  FROM "
			+ "    tbl_document_master d "
			+ "  WHERE d.application_no = a.application_no) AS documents "
			+ "FROM "
			+ "  tbl_programme_trainee_enrollment_dtls a "
			+ "WHERE a.id = ?", nativeQuery = true)
	List<Tuple> getTraineeDetailsById(String traineeId);
	
}
