package com.moesd.tvet.mis.backend.application.repository;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com.moesd.tvet.mis.backend.application.model.InstituteRegistrationDetails;

import jakarta.persistence.Tuple;

public interface InstituteRegistrationDetailsRepository extends JpaRepository<InstituteRegistrationDetails, Long> {
	
	@Query(value = "SELECT * FROM tbl_institute_registration_dtls " + "WHERE registration_no = ?", nativeQuery = true)
	List<Tuple> getInstituteDetails(String registration_no);
	
	@Query(value = "SELECT "
			+ "  ir.application_no, "
			+ "  ir.proposed_institute_name, "
			+ "  ir.dzongkhag_id, "
			+ "  ir.exact_location, "
			+ "  ir.telephone_no, "
			+ "  ir.mobile_no, "
			+ "  ir.email_id, "
			+ "  ir.service_id, "
			+ "  ir.website, "
			+ "  ir.ownership_type_id, "
			+ "  ir.bhutanese_employees, "
			+ "  ir.non_bhutanese_employees, "
			+ "  ir.business_license_no, "
			+ "  ir.key_contact_name, "
			+ "  ir.key_contact_designation, "
			+ "  ir.key_contact_mobile_no, "
			+ "  ir.status_id, "
			+ "  ir.created_at, "
			+ "  ir.created_by, "
			+ "  ir.updated_at, "
			+ "  ir.updated_by, "
			+ "  (SELECT "
			+ "    JSON_ARRAYAGG( "
			+ "      JSON_OBJECT( "
			+ "        'id', "
			+ "        t.id, "
			+ "        'nationalityId', "
			+ "        t.nationality_id, "
			+ "        'cid', "
			+ "        t.cid, "
			+ "        'workPermit', "
			+ "        t.work_permit, "
			+ "        'name', "
			+ "        t.name, "
			+ "        'genderId', "
			+ "        t.gender_id, "
			+ "        'qualification', "
			+ "        t.qualification, "
			+ "        'experience', "
			+ "        t.experience, "
			+ "        'typeId', "
			+ "        t.type_id "
			+ "      ) "
			+ "    ) "
			+ "  FROM "
			+ "    tbl_institute_registration_trainer_app t "
			+ "  WHERE t.application_no = ir.application_no) AS trainers, "
			+ "  (SELECT "
			+ "    JSON_ARRAYAGG( "
			+ "      JSON_OBJECT( "
			+ "        'id', "
			+ "        c.id, "
			+ "        'sectorId', "
			+ "        c.sector_id, "
			+ "        'courseId', "
			+ "        c.course_id, "
			+ "        'theoryHours', "
			+ "        c.theory_hours, "
			+ "        'practicalHours', "
			+ "        c.practical_hours, "
			+ "        'ojtHours', "
			+ "        c.ojt_hours, "
			+ "        'feesPerTrainee', "
			+ "        c.fees_per_trainee, "
			+ "        'enrollmentCapacity', "
			+ "        c.enrollment_capacity, "
			+ "        'courseLevelId', "
			+ "        c.course_level_id "
			+ "      ) "
			+ "    ) "
			+ "  FROM "
			+ "    tbl_institute_registration_course_app c "
			+ "  WHERE c.application_no = ir.application_no) AS courses, "
			+ "  (SELECT "
			+ "    JSON_ARRAYAGG( "
			+ "      JSON_OBJECT( "
			+ "        'id', "
			+ "        q.id, "
			+ "        'standardId', "
			+ "        q.standard_id, "
			+ "        'responseId', "
			+ "        q.response_id, "
			+ "        'remarks', "
			+ "        q.remarks "
			+ "      ) "
			+ "    ) "
			+ "  FROM "
			+ "    tbl_institute_registration_quality_response_app q "
			+ "  WHERE q.application_no = ir.application_no) AS quality_standard_responses, "
			+ "  (SELECT "
			+ "    JSON_ARRAYAGG( "
			+ "      JSON_OBJECT( "
			+ "        'id', "
			+ "        ui.id, "
			+ "        'classLevel', "
			+ "        ui.class_level, "
			+ "        'duration', "
			+ "        ui.duration, "
			+ "        'fees', "
			+ "        ui.fees, "
			+ "        'subjects', "
			+ "        ui.subject, "
			+ "        'tutorCid', "
			+ "        ui.tutor_cid, "
			+ "        'tutorName', "
			+ "        ui.tutor_name, "
			+ "        'tutorQualification', "
			+ "        ui.tutor_qualification "
			+ "      ) "
			+ "    ) "
			+ "  FROM "
			+ "    tbl_institute_registration_tuition_details ui "
			+ "  WHERE ui.application_no = ir.application_no) AS tuition_details, "
			+ "  (SELECT "
			+ "    JSON_ARRAYAGG( "
			+ "      JSON_OBJECT( "
			+ "        'id', "
			+ "        d.id, "
			+ "        'documentName', "
			+ "        d.document_name, "
			+ "        'url', "
			+ "        d.upload_url "
			+ "      ) "
			+ "    ) "
			+ "  FROM "
			+ "    tbl_document_master d "
			+ "  WHERE d.application_no = ir.application_no) AS documents "
			+ "FROM "
			+ "  tbl_institute_registration_dtls ir "
			+ "WHERE ir.registration_no = ?", nativeQuery = true)
	List<Tuple> getInstituteRenewalDetails(String registration_no);
	
	@Query(value =    "SELECT "
			+ "  p.id, "
			+ "  p.service_id, "
			+ "  p.application_no, "
			+ "  p.ownership_type_id, "
			+ "  p.registration_no, "
			+ "  p.company_name, "
			+ "  p.proposed_institute_name, "
			+ "  p.dzongkhag_id, "
			+ "  p.exact_location, "
			+ "  p.telephone_no, "
			+ "  p.mobile_no, "
			+ "  p.email_id, "
			+ "  p.sector_id, "
			+ "  p.course_id, "
			+ "  p.activity_level_id, "
			+ "  p.other_ownership_type_id, "
			+ "  p.other_name, "
			+ "  p.other_address, "
			+ "  p.promoter_citizen_id, "
			+ "  p.promoter_name, "
			+ "  p.status_id, "
			+ "  (SELECT "
			+ "    JSON_ARRAYAGG( "
			+ "      JSON_OBJECT( "
			+ "        'id', "
			+ "        pp.id, "
			+ "        'typeOfOwnerId', "
			+ "        pp.type_of_owner_id, "
			+ "        'partnerCidNo', "
			+ "        pp.partner_cid_no, "
			+ "        'partnerName', "
			+ "        pp.partner_name, "
			+ "        'partnerCompanyRegistrationNo', "
			+ "        pp.partner_company_registration_no, "
			+ "        'partnerCompanyName', "
			+ "        pp.partner_company_name "
			+ "      ) "
			+ "    ) "
			+ "  FROM "
			+ "    tbl_institute_proposal_partnership pp "
			+ "  WHERE pp.application_no = p.application_no) AS partnerships "
			+ "FROM "
			+ "  tbl_institute_proposal p "
			+ "  LEFT JOIN tbl_institute_registration_app rp "
			+ "  ON p.application_no = rp.proposal_application_no "
			+ "  LEFT JOIN tbl_institute_registration_dtls ipr "
			+ "  ON ipr.application_no = rp.application_no "
			+ "WHERE ipr.registration_no = ?", nativeQuery = true)
	List<Tuple> getInstituteChangeDetails(String registration_no);
	
	
	
	@Query(value =  "SELECT "
			+ "  a.*, "
			+ "  a.proposed_institute_name AS institute_name "
			+ "FROM "
			+ "  tbl_institute_registration_dtls a "
			+ "WHERE a.institute_id = ?", nativeQuery = true)
	List<Tuple> getInstituteNameByInstituteId(String registration_no);
	
	Optional<InstituteRegistrationDetails> findByRegistrationNo(String registrationNo);
	
}
