package com.moesd.tvet.mis.backend.application.repository;

import java.util.List;
import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import com.moesd.tvet.mis.backend.application.model.InstituteRegistrationApp;

import jakarta.persistence.Tuple;

public interface InstituteRegistrationRepository extends JpaRepository<InstituteRegistrationApp, Long> {

	@Query(value =  
			"SELECT "
					+ "  b.status_id, "
					+ "  a.status_id AS registration_status_id "
					+ "FROM "
					+ "  tbl_institute_registration_app a "
					+ "  RIGHT JOIN tbl_institute_proposal b "
					+ "    ON b.application_no = a.proposal_application_no "
					+ "WHERE b.application_no = ?1", nativeQuery = true)
		List<Tuple> findByProposalApplicationNo(String application_no);
	
	
	Optional<InstituteRegistrationApp> findInstituteRegistrationByApplicationNo(String applicationNo);
	
	@Query(value =  
			"SELECT "
					+ "  ir.id, "
					+ "  ir.application_no, "
					+ "  ir.proposal_application_no, "
					+ "  ir.proposed_institute_name, "
					+ "  ir.dzongkhag_id, "
					+ "  ir.exact_location, "
					+ "  ir.telephone_no, "
					+ "  ir.mobile_no, "
					+ "  ir.email_id, "
					+ "  ir.sector_id, "
					+ "  ir.service_id, "
					+ "  ir.website, "
					+ "  ir.ownership_type_id, "
					+ "  ir.bhutanese_employees, "
					+ "  ir.non_bhutanese_employees, "
					+ "  ir.business_license_no, "
					+ "  ir.key_contact_name, "
					+ "  ir.key_contact_designation, "
					+ "  ir.key_contact_mobile_no, "
					+ "  ir.status_id, "
					+ "  ir.created_at, "
					+ "  ir.created_by, "
					+ "  ir.updated_at, "
					+ "  ir.updated_by, "
					+ "  (SELECT "
					+ "    JSON_ARRAYAGG( "
					+ "      JSON_OBJECT( "
					+ "        'id', "
					+ "        t.id, "
					+ "        'nationalityId', "
					+ "        t.nationality_id, "
					+ "        'cid', "
					+ "        t.cid, "
					+ "        'workPermit', "
					+ "        t.work_permit, "
					+ "        'name', "
					+ "        t.name, "
					+ "        'genderId', "
					+ "        t.gender_id, "
					+ "        'qualification', "
					+ "        t.qualification, "
					+ "        'experience', "
					+ "        t.experience, "
					+ "        'typeId', "
					+ "        t.type_id "
					+ "      ) "
					+ "    ) "
					+ "  FROM "
					+ "    tbl_institute_registration_trainer_app t "
					+ "  WHERE t.application_no = ir.application_no) AS trainers, "
					+ "  (SELECT "
					+ "    JSON_ARRAYAGG( "
					+ "      JSON_OBJECT( "
					+ "        'id', "
					+ "        c.id, "
					+ "        'courseTitle', "
					+ "        c.course_title, "
					+ "        'theoryHours', "
					+ "        c.theory_hours, "
					+ "        'practicalHours', "
					+ "        c.practical_hours, "
					+ "        'ojtHours', "
					+ "        c.ojt_hours, "
					+ "        'feesPerTrainee', "
					+ "        c.fees_per_trainee, "
					+ "        'enrollmentCapacity', "
					+ "        c.enrollment_capacity, "
					+ "        'courseLevelId', "
					+ "        c.course_level_id "
					+ "      ) "
					+ "    ) "
					+ "  FROM "
					+ "    tbl_institute_registration_course_app c "
					+ "  WHERE c.application_no = ir.application_no) AS courses, "
					+ "  (SELECT "
					+ "    JSON_ARRAYAGG( "
					+ "      JSON_OBJECT( "
					+ "        'id', "
					+ "        q.id, "
					+ "        'standardId', "
					+ "        q.standard_id, "
					+ "        'responseId', "
					+ "        q.response_id "
					+ "      ) "
					+ "    ) "
					+ "  FROM "
					+ "    tbl_institute_registration_quality_response_app q "
					+ "  WHERE q.application_no = ir.application_no) AS quality_standard_responses, "
					+ "  (SELECT "
					+ "    JSON_ARRAYAGG( "
					+ "      JSON_OBJECT( "
					+ "        'id', "
					+ "        d.id, "
					+ "        'documentName', "
					+ "        d.document_name, "
					+ "        'url', "
					+ "        d.upload_url "
					+ "      ) "
					+ "    ) "
					+ "  FROM "
					+ "    tbl_document_master d "
					+ "  WHERE d.application_no = ir.application_no) AS documents "
					+ "FROM "
					+ "  tbl_institute_registration_app ir "
					+ "WHERE ir.application_no = ?", nativeQuery = true)
		List<Tuple> getInstituteRegistrationDetails(String application_no);
	
		

}
